### ISSUE TITLE
KeyError: 'site' In attack.py line 129

### ISSUE THREAD

**Issue by look-its-ashton** [AlexTrushkovsky/NoWarDDoS#28]
My program ends with:

Traceback (most recent call last):
  File "/nowarddos/attack.py", line 192, in <module>
    status, site = task.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nowarddos/attack.py", line 129, in mainth
    site = unquote(choice(targets) if targets else data['site']['page'])
KeyError: 'site'
saving to /nowarddos/attack.py
Success update

**Comment by Konark-Web** [comment]
I have this problem too

**Comment by dariy-vel** [comment]
The problem was due to the hosts provider being down. We've fixed that and moved hosts endpoint.
